openapi: 3.0.0
info:
  title: Library Management API
  version: 1.0.0
  description: A simple CRUD API for managing books

servers:
  - url: http://localhost:4000/api/v1
    description: Local development server

tags:
  - name: Books
    description: API endpoints for managing books

paths:
  /books:
    get:
      tags: [Books]
      summary: Get all books
      responses:
        '200':
          description: List of all books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
              examples:
                success:
                  summary: A sample book list
                  value:
                    - id: "123e4567-e89b-12d3-a456-426614174000"
                      title: "Things Fall Apart"
                      author: "Chinua Achebe"
                      genre: "African literature"
                      image: "https://example.com/achebe.jpg"
                      ratings: 4.9
                      price: 12.99

    post:
      tags: [Books]
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
              examples:
                created:
                  summary: Example of a created book
                  value:
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    title: "Things Fall Apart"
                    author: "Chinua Achebe"
                    genre: "African literature"
                    image: "https://example.com/achebe.jpg"
                    ratings: 4.9
                    price: 12.99
        '400':
          description: Validation error

  /books/{id}:
    get:
      tags: [Books]
      summary: Get a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Book found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
              examples:
                found:
                  summary: A sample single book
                  value:
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    title: "Things Fall Apart"
                    author: "Chinua Achebe"
                    genre: "African literature"
                    image: "https://example.com/achebe.jpg"
                    ratings: 4.9
                    price: 12.99
        '404':
          description: Book not found

    put:
      tags: [Books]
      summary: Update a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found

    delete:
      tags: [Books]
      summary: Delete a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Book deleted successfully
        '404':
          description: Book not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          example: "The Tale of the Brave"
        author:
          type: string
          example: "Jane Smith"
        genre:
          type: string
          example: "Fiction"
        image:
          type: string
          format: uri
          example: "https://example.com/book.jpg"
        ratings:
          type: number
          minimum: 0
          maximum: 5
          example: 4.7
        price:
          type: number
          example: 19.99

    BookInput:
      type: object
      required:
        - title
        - author
        - genre
        - image
        - ratings
      properties:
        title:
          type: string
          example: "Things Fall Apart"
        author:
          type: string
          example: "Chinua Achebe"
        genre:
          type: string
          example: "African literature"
        image:
          type: string
          format: uri
          example: "https://example.com/achebe.jpg"
        ratings:
          type: number
          example: 4.9
        price:
          type: number
          example: 12.99
